services:
  api:
    build:
      context: .
      target: builder
    container_name: fastapi-application
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - API_URL=${API_URL}
      - PORT=8000
    ports:
      - "50100:8000"

    restart: "unless-stopped"